# CONFIGURATION DATABASE 
version: '3'
services: 
  db:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - ./db:/var/lib/mysql
    expose:
     - 3306

  php-my-admin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      UPLOAD_LIMIT: 300M
    ports:
     - 8081:80

networks:
   default:
    external:
        name: wordpress-sites
