# CONFIGURATION DATABASE 
version: '3'
services: 
  db:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=  
    volumes:
    - ./db:/var/lib/mysql

networks:
   default:
    external:
        name: wordpress-sites