version: '3'
services: 
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: unless-stopped
        volumes:
            - certs:/etc/nginx/certs:ro
            - confd:/etc/nginx/conf.d
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        
    letsencrypt:
         image: duch/letsencrypt-nginx-proxy-companion:stable
         restart: unless-stopped
         volumes:
            - certs:/etc/nginx/certs:rw
            - confd:/etc/nginx/conf.d
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro        

networks:
    default:
        external:
            name: wordpress-sites
        
volumes:
    certs:
    html:
    vhostd:
    confd:
